INSERT INTO PoliceStation(PSID,stationAddress,stationRating) VALUES ('1','Cluj',5);



INSERT INTO EMPLOYEE VALUES(111,'Imre','Toth',44,3,'10/05/99',1);


INSERT INTO GunLicense VALUES(111,'03/03/13','10/10/19');


INSERT INTO EMPLOYEE VALUES(121,'DA','DA',10,3,'10/05/99',1);


UPDATE EMPLOYEE SET casesSolved=14 WHERE hoursWorked BETWEEN 30 AND 50;

INSERT INTO EMPLOYEE VALUES(131,'DA','DA',100,33,'',1);

DELETE FROM EMPLOYEE WHERE casesSolved IS NULL AND firstName LIKE  '%DA%';


UPDATE GunLicense SET DateOfExpiration='10/12/24' WHERE EID IN (SELECT EID FROM EMPLOYEE);


--SELECT QUERIES
SELECT * FROM EMPLOYEE WHERE EID=111 UNION SELECT * FROM EMPLOYEE WHERE hoursWorked <=100 AND dateOfBirth IS NOT NULL ORDER BY hoursWorked;



SELECT * FROM EMPLOYEE WHERE hoursWorked >=10 AND hoursWorked <=40 INTERSECT SELECT * FROM EMPLOYEE WHERE casesSolved >= 10;


SELECT * FROM EMPLOYEE WHERE EID IS NOT NULL EXCEPT SELECT * FROM EMPLOYEE WHERE NOT PSID=111 ORDER BY hoursWorked ;


SELECT * FROM PoliceStation p INNER JOIN EMPLOYEE e on p.PSID = e.PSID INNER JOIN GunLicense g ON g.EID=e.EID;


SELECT * FROM PoliceStation p LEFT JOIN EMPLOYEE e on p.PSID = e.PSID LEFT JOIN GunLicense g ON g.EID=e.EID;


SELECT * FROM PoliceStation p RIGHT JOIN EMPLOYEE e on p.PSID = e.PSID RIGHT JOIN GunLicense g ON g.EID=e.EID;


SELECT * FROM PoliceStation p FULL JOIN EMPLOYEE e on p.PSID = e.PSID FULL JOIN GunLicense g ON g.EID=e.EID;


SELECT DISTINCT DateOfAdmission,DateOfExpiration FROM GunLicense g WHERE g.EID IN (SELECT EID FROM EMPLOYEE);


SELECT TOP 10 DateOfAdmission,DateOfExpiration FROM GunLicense g WHERE EXISTS (SELECT EID FROM EMPLOYEE e WHERE e.EID = g.EID);


SELECT g.PSID  FROM (SELECT * FROM PoliceStation) g;


SELECT g.EID FROM GunLicense g INNER JOIN EMPLOYEE e ON g.EID = e.EID GROUP BY g.EID


SELECT g.EID FROM GunLicense g INNER JOIN EMPLOYEE e ON g.EID = e.EID GROUP BY g.EID HAVING g.EID <=100;


SELECT g.EID FROM GunLicense g INNER JOIN EMPLOYEE e ON g.EID = e.EID GROUP BY g.EID HAVING MIN(g.EID) >= 120;

SELECT g.EID FROM GunLicense g  INNER JOIN EMPLOYEE e on g.EID = e.EID  GROUP BY g.EID HAVING g.EID IN (SELECT e.EID FROM EMPLOYEE e WHERE e.casesSolved >= 0)